[general]
name = "relu"
universal = false

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.activation]
backend = "cuda"
cuda-capabilities = ["8.0"]
depends = ["torch"]
src = ["relu_cuda/relu.cu"]
